// This file is used for dev env

export const Environment = {
  homePath: '/p/creative',
  appName: 'Creative Library Dev (LTS 2019)',
  nuxeoUrl: 'http://100.122.3.142:8080/nuxeo/',
  forgotPassword: 'https://register.adauth.me/nam/help',
  backslashAPPUrl: 'http://100.122.3.142:8080/nuxeo/edges',
  siteAssetPath: '/nuxeo/LibraryWebUI/',
  production: true,
  autoLogin: true,
};

export const NUXEO_META_INFO = {
  ROOT_FOLDER_PATH: '/',
  CREATIVE_BASE_FOLDER_PATH: '/Creative',
  CREATIVE_AWARD_FOLDER_PATH: '/Creative/AWARDS',
  CREATIVE_IMAGE_VIDEO_TYPES: '["App-Library-Image", "App-Library-Video"]',
  CREATIVE_IMAGE_VIDEO_AUDIO_TYPES: '["App-Library-Image", "App-Library-Video", "App-Library-Audio"]',
  CREATIVE_FOLDER_TYPES: '["App-Library-Folder"]',
  CREATIVE_PROJECT_TYPES: '["App-Library-Project"]',
  CREATIVE_BRAND_FOLDER_TYPE: '["Brand Folder"]',
  BACKSLASH_BASE_FOLDER_PATH: '/know-edge/-backslash',
  BACKSLASH_ASSET_PAGE_PROVIDER: 'creative_website_backslash_related_assets',
  DISRUPTION_BASE_FOLDER_PATH: '/know-edge/Disruption',
  DISRUPTION_DAYS_PATH: '/know-edge/Disruption/Disruption Days',
  DISRUPTION_ROAD_PATH: '/know-edge/Disruption/Disruption Road Maps/',
  DISRUPTION_THEORY_PATH: '/know-edge/Disruption/Disruption Theory/',
  DISRUPTION_DAYS_TYPE: '["App-Disruption-Day"]',
  DISRUPTION_DAY_TYPE: '["App-Disruption-Asset"]',
  DISRUPTION_ASSET_PAGE_PROVIDER: 'creative_website_disruption_related_assets',
  INTELLIGENCE_BASE_FOLDER_PATH: '/know-edge/Intelligence',
  INTELLIGENCE_FOLDER_TYPE: '["App-Intelligence-Consumer-Folder", "App-Intelligence-Industry-Folder", "App-Intelligence-Marketing-Folder" ]',
  INTELLIGENCE_INDUSTRY_TYPE: '["App-Intelligence-Industry"]',
  INTELLIGENCE_ASSET_TYPE: '["App-Intelligence-Asset"]',
  INTELLIGENCE_ASSET_PAGE_PROVIDER: 'creative_website_intelligence_related_assets',
  KNOWEDGE_BASIC_PATH: '/know-edge',
  INTELLIGENCE_BACKGROUND_PATH: '/Creative/1. GCL Frontpage/Banners/Intelligence/',
  BACKGROUND_TYPE: '["App-Library-Image"]',
  HOME_BACKGROUND_PATH: '/Creative/1. GCL Frontpage/Banners/Oliver Kahn Arches Bridg/',
};
