
export const Environment = {
  title: 'Know\\edge',
  homePath: '/p/creative',
  appName: 'Creative Library',
  nuxeoUrl: '/nuxeo/',
  backslashAppUrl: '/nuxeo/edges',
  assetPath: '/nuxeo/LibraryWebUI/',
  oauth2CallBackPath: '/nuxeo/site/LibraryWebUI/#/',
  production: true,
};

export enum NUXEO_PATH_INFO {
  KNOWEDGE_BASIC_PATH = '/know-edge/',
  CREATIVE_BASE_FOLDER_PATH = '/Creative/',
  CREATIVE_TBWA_FOLDER_PATH = '/Creative/TBWA-/',
  CREATIVE_AWARD_FOLDER_PATH = '/Creative/AWARDS/',
  CREATIVE_BEST_ASSETS_PATH = '/Creative/1. GCL Frontpage/Frontpage Assets/',
  BACKSLASH_BASE_FOLDER_PATH = '/know-edge/-backslash/',
  DISRUPTION_BASE_FOLDER_PATH = '/know-edge/Disruption/',
  DISRUPTION_DAYS_PATH = '/know-edge/Disruption/Disruption Days/',
  DISRUPTION_ROADMAPS_PATH = '/know-edge/Disruption/Disruption Roadmaps/',
  DISRUPTION_THEORY_PATH = '/know-edge/Disruption/Disruption How Tos/',
  DISRUPTION_THINKING_PATH = '/know-edge/Disruption/Brilliant Thinking/',
  DISRUPTION_AWARD_FOLDER_PATH = '/know-edge/Disruption/Disruption Awards/Carousel/',
  INTELLIGENCE_BASE_FOLDER_PATH = '/know-edge/Intelligence/',
  BIZ_DEV_BASE_FOLDER_PATH = '/know-edge/Business Development/',
  BIZ_DEV_10X_FOLDER_PATH = '/know-edge/Business Development/10x/',
  BIZ_DEV_CASE_STUDIES_FOLDER_PATH = '/know-edge/Business Development/Case Studies/',
  BIZ_DEV_THOUGHT_LEADERSHIP_FOLDER_PATH = '/know-edge/Business Development/Thought Leadership/',
  FRONTPAGE_BANNER_PATH = '/Creative/1. GCL Frontpage/Banners/',
}

export enum NUXEO_META_INFO {
  CREATIVE_IMAGE_VIDEO_TYPES = '["App-Library-Image", "App-Library-Video"]',
  CREATIVE_IMAGE_VIDEO_AUDIO_TYPES = '["App-Library-Image", "App-Library-Video", "App-Library-Audio"]',
  CREATIVE_FOLDER_TYPE = '["App-Library-Folder"]',
  CREATIVE_PROJECT_TYPE = '["App-Library-Project"]',
  CREATIVE_CAMPAIGN_TYPE = '["App-Library-Campaign"]',
  CREATIVE_CAMPAIGN_FOLDER_TYPE = '["App-Library-Campaign-Mgt-Folder"]',
  CREATIVE_UR_FOLDER_TYPE = '["App-Library-UR-Folder"]',
  CREATIVE_BRAND_FOLDER_TYPE = '["Brand Folder"]',
  CREATIVE_SELECTED_BRAND_TYPE = '["App-Library-Selected-Brand"]',
  CREATIVE_AGENCY_FOLDER_TYPE = '["Agency Folder"]',
  CREATIVE_AGENCY_AND_BRAND_FOLDER_TYPE = '["Brand Folder", "Agency Folder"]',
  CREATIVE_UR_CONTRACT_TYPES = '["App-Library-UsageRights-Talent", "App-Library-UsageRights-Music", "App-Library-UsageRights-Photographer", "App-Library-UsageRights-Stock"]',
  BACKSLASH_ARTICLE_VIDEO_TYPES = '["App-Backslash-Article", "App-Backslash-Video"]',
  DISRUPTION_DAYS_TYPE = '["App-Disruption-Day"]',
  DISRUPTION_DAY_ASSET_TYPES = '["App-Disruption-Asset", "App-Disruption-Day-Asset"]',
  DISRUPTION_ROADMAP_TYPE = '["App-Disruption-Roadmap-Asset"]',
  DISRUPTION_THEORY_TYPE = '["App-Disruption-Theory-Asset"]',
  DISRUPTION_THINKING_TYPE = '["App-Disruption-Asset"]',
  DISRUPTION_ROADMAP_FOLDER_TYPE = '["App-Disruption-Roadmap-Folder"]',
  DISRUPTION_DAYS_FOLDER_TYPE = '["App-Disruption-Days-Folder"]',
  DISRUPTION_THEORY_FOLDER_TYPE = '["App-Disruption-Theory-Folder"]',
  DISRUPTION_THINKING_FOLDER_TYPE = '["App-Disruption-Folder"]',
  DISRUPTION_FOLDER_TYPE = '["App-Disruption-Roadmap-Folder", "App-Disruption-Days-Folder", "App-Disruption-Theory-Folder", "App-Disruption-Folder"]',
  DISRUPTION_ASSET_TYPE = '["App-Disruption-Asset", "App-Disruption-Roadmap-Asset", "App-Disruption-Theory-Asset", "App-Disruption-Day-Asset", "App-Disruption-Day"]',
  DISRUPTION_AWARD_ASSET_TYPE = '["App-Disruption-Awards-Asset"]',
  DISRUPTION_AWARD_FOLDER_TYPE = '["App-Disruption-Awards-Folder"]',
  INTELLIGENCE_FOLDER_TYPE = '["App-Intelligence-Consumer-Folder", "App-Intelligence-Industry-Folder", "App-Intelligence-Marketing-Folder"]',
  INTELLIGENCE_BASE_FOLDER_TYPE = '["App-Intelligence-Folder"]',
  INTELLIGENCE_BRANDS_TYPE = '["App-Intelligence-Brands-Folder"]',
  INTELLIGENCE_INDUSTRY_TYPE = '["App-Intelligence-Industry"]',
  INTELLIGENCE_ASSET_TYPE = '["App-Intelligence-Asset"]',
  INTELLIGENCE_ALL_FOLDERS = '["App-Intelligence-Consumer-Folder", "App-Intelligence-Industry-Folder", "App-Intelligence-Marketing-Folder", "App-Intelligence-Industry", "App-Intelligence-Brands-Folder"]',
  BIZ_DEV_CASE_STUDIES_BASE_FOLDER_TYPE = '["App-BizDev-Case-Studies-Folder"]',
  BIZ_DEV_CASE_STUDIES_FOLDER_TYPE = '["App-BizDev-CaseStudy-Folder"]',
  BIZ_DEV_CASE_STUDIES_ASSET_TYPE = '["App-BizDev-CaseStudy-Asset"]',
  BIZ_DEV_CASE_STUDIES_SUB_FOLDER_TYPE = '["App-BizDev-CaseStudy-Folder", "App-BizDev-CaseStudy-Asset"]',
  BIZ_DEV_THOUGHT_LEADERSHIP_FOLDER_TYPE = '["App-BizDev-ThoughtLeadership-Folder"]',
  BIZ_DEV_THOUGHT_LEADERSHIP_SUB_FOLDER_TYPE = '["App-BizDev-Thought-Folder", "App-BizDev-Thought-Asset"]',
  BIZ_DEV_SUB_FOLDER_TYPES = '["App-BizDev-Case-Studies-Folder", "App-BizDev-ThoughtLeadership-Folder"]',
  BIZ_DEV_SEARCH_TYPE = '["App-BizDev-CaseStudy-Folder", "App-BizDev-CaseStudy-Asset", "App-BizDev-Thought-Folder", "App-BizDev-Thought-Asset"]',
  BIZ_DEV_FOLDER_TYPE = '["App-BizDev-Folder"]',
  BIZ_DEV_ASSET_TYPE = '["App-BizDev-CaseStudy-Asset", "App-BizDev-Thought-Asset"]',
  FRONTPAGE_BANNER_TYPE = '["App-Library-Image"]',
  BACKSLASH_ASSET_PAGE_PROVIDER = 'creative_website_backslash_related_assets',
  DISRUPTION_ASSET_PAGE_PROVIDER = 'creative_website_disruption_related_assets',
  INTELLIGENCE_ASSET_PAGE_PROVIDER = 'creative_website_intelligence_related_assets',
}
