import { NgModule } from '@angular/core';
import { ThemeModule } from '@theme/theme.module';
import { DocumentFormModule } from '../document-form/document-form.module';
import { GlobalDocumentFormComponent } from './global-document-form.component';
import { DocumentBatchOperationModule } from '../document-batch-operation/document-batch-operation.module';
import {
  CreativeAssetImageFormComponent,
  CreativeAssetVideoFormComponent,
  CreativeAssetAudioFormComponent,
  CreativeAssetBrandFormComponent,
  CreativeUsageRightsModelComponent,
  CreativeUsageRightsMusicComponent,
  CreativeUsageRightsPhotoComponent,
  CreativeUsageRightsStockComponent,
  CreativeCampaignFormComponent,
  CreativeProjectFormComponent,
  CreativeRingCollectionFormComponent,
  CreativeRingCollectionUploadFormComponent,
  CreativeRingBrandCollectionFormComponent,
  CreativeRingAssetFormComponent,
  DisruptionRoadmapFormComponent,
  DisruptionBrilliantThinkingFormComponent,
  DisruptionDayFolderFormComponent,
  DisruptionDayAssetFormComponent,
  DisruptionHowTosAssetFormComponent,
  DisruptionXModuleAssetFormComponent,
  IntelligenceBrandsFormComponent,
  IntelligenceAssetFormComponent,
  BizDevOpportunityAssetFormComponent,
  BizDevOpportunityFolderFormComponent,
  BizDevCaseStudyFolderFormComponent,
  BizDevCaseStudyAssetFormComponent,
  BizDevThoughtFolderFormComponent,
  BizDevThoughtAssetFormComponent,
  InnovationAssetFormComponent,
  InnovationFolderFormComponent,
  BackslashAssetPostFormComponent,
  BackslashAssetVideoFormComponent,
  BackslashCaseStudyAssetFormComponent,
  BackslashCaseStudyFolderFormComponent,
  BackslashCaseStudyCategoryFormComponent,
  BackslashEdgesAssetFormComponent,
  BackslashEdgesFolderFormComponent,
  BackslashResourcesAssetFormComponent,
  BackslashResourcesFolderFormComponent,
  BackslashTriggerFormComponent,
  BackslashPluginTriggerFormComponent,
  BackslashPluginUserPreferenceFormComponent,
  LearningProgramFormComponent,
} from '../global-document-form';

const COMPONENTS = [
  CreativeAssetImageFormComponent,
  CreativeAssetVideoFormComponent,
  CreativeAssetAudioFormComponent,
  CreativeAssetBrandFormComponent,
  CreativeUsageRightsModelComponent,
  CreativeUsageRightsMusicComponent,
  CreativeUsageRightsPhotoComponent,
  CreativeUsageRightsStockComponent,
  CreativeCampaignFormComponent,
  CreativeProjectFormComponent,
  CreativeRingCollectionUploadFormComponent,
  CreativeRingCollectionFormComponent,
  CreativeRingBrandCollectionFormComponent,
  CreativeRingAssetFormComponent,
  DisruptionRoadmapFormComponent,
  DisruptionBrilliantThinkingFormComponent,
  DisruptionDayFolderFormComponent,
  DisruptionDayAssetFormComponent,
  DisruptionHowTosAssetFormComponent,
  DisruptionXModuleAssetFormComponent,
  IntelligenceBrandsFormComponent,
  IntelligenceAssetFormComponent,
  BizDevOpportunityAssetFormComponent,
  BizDevOpportunityFolderFormComponent,
  BizDevCaseStudyFolderFormComponent,
  BizDevCaseStudyAssetFormComponent,
  BizDevThoughtFolderFormComponent,
  BizDevThoughtAssetFormComponent,
  InnovationAssetFormComponent,
  InnovationFolderFormComponent,
  BackslashAssetPostFormComponent,
  BackslashAssetVideoFormComponent,
  BackslashCaseStudyAssetFormComponent,
  BackslashCaseStudyFolderFormComponent,
  BackslashCaseStudyCategoryFormComponent,
  BackslashEdgesAssetFormComponent,
  BackslashEdgesFolderFormComponent,
  BackslashResourcesAssetFormComponent,
  BackslashResourcesFolderFormComponent,
  BackslashTriggerFormComponent,
  BackslashPluginTriggerFormComponent,
  BackslashPluginUserPreferenceFormComponent,
  LearningProgramFormComponent,
  GlobalDocumentFormComponent,
];

@NgModule({
  imports: [
    ThemeModule,
    DocumentFormModule,
    DocumentBatchOperationModule,
  ],
  declarations: [
    ...COMPONENTS,
  ],
  exports: [
    ...COMPONENTS,
  ],
})
export class GlobalDocumentFormModule { }
